development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: appacademy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: app_test
  pool: 5
  username: appacademy
  password: